language: php

stage: tests

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

before_install:
  - nvm install 12
  - npm i -g npm@7
  - phpenv config-rm xdebug.ini || return 0

install:
  - composer remove --dev phpunit/phpunit friendsofphp/php-cs-fixer vimeo/psalm phpspec/prophecy-phpunit
  - composer config --unset platform.php
  - composer update
  - composer require --dev phpunit/phpunit ^5

script:
  - php ./tests/phpunit-phar.php tests
  - php ./vendor/bin/phpunit tests

services:
  - mysql

stages:
  - analysis
  - tests

jobs:
  allow_failures:
    - php: nightly
    - env: analysis_type="composer analyze"

  include:
    - php: 5.6
      install:
        - composer remove --dev phpunit/phpunit friendsofphp/php-cs-fixer vimeo/psalm phpspec/prophecy-phpunit
        - composer config --unset platform.php
        - composer update
        - composer require --dev phpunit/phpunit ^5

    - php: 7.4
      install:
        - composer install

    - php: 8.0
      install:
        - composer install

    - php: nightly
      install:
        - composer remove --dev friendsofphp/php-cs-fixer vimeo/psalm
        - composer update

    # Check if `composer format` was run correctly
    - stage: analysis
      php: 7.4
      install: composer install
      script:
        - composer format
        - git status # Required to flush the cache
        - git diff-files --quiet --exit-code
      env: analysis_type="composer format"

    # Check if `composer build` was run correctly
    - stage: analysis
      php: 7.4
      install: composer install
      script:
        - composer clean
        # - composer build
        # Travis is broken and screws with permissions. This breaks the build.
        # Instead we build sass and js then manually fix permissions before
        # building the phar file to ensure reproducibility.
        - composer build:sass
        - composer build:js
        - chmod -R g-w .
        - composer build:php
        - git status # Required to flush the cache
        - git diff-files --quiet --exit-code
      env: analysis_type="composer build"

    # Check if code passes phpstan/psalm static analysis
    - stage: analysis
      php: 7.4
      install: composer install
      script: composer analyze
      env: analysis_type="composer analyze"

    # Preliminary test run
    - stage: analysis
      php: 7.4
      install: composer install
      script: php ./vendor/bin/phpunit tests
